general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(9ccfd8ff) rgba(e0def4ff) 45deg
    col.inactive_border = rgba(26233aff)
}
