[colors.primary]
background = "#282828" # dark0
foreground = "#d4be98" # light1

[colors.normal]
black   = "#3c3836" # dark1
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#fe8019" # ORANGE (stronger than default gruvbox yellow)
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"

[colors.bright]
black   = "#504945"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#fabd2f" # keep consistent orange
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#ebdbb2"

[colors.dim]
black   = "#3c3836"
red     = "#c14a4a"
green   = "#8f9a52"
yellow  = "#d65d0e"
blue    = "#6f8f8f"
magenta = "#b16286"
cyan    = "#7daea3"
white   = "#bdae93"

