general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(a89984ff) rgba(ebdbb2ff) 45deg
    col.inactive_border = rgba(3c3836ff)
}
