general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(8a8a8dff) rgba(bebebeff) 45deg
    col.inactive_border = rgba(333333ff)
}
