general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(f5eafdff) rgba(f5eafdff) 45deg
    col.inactive_border = rgba(2a1f3fff)
}
