general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(b96e5aff) rgba(d57d63ff) 45deg
    col.inactive_border = rgba(474040ff)
}
