# Hellpaper Configuration File
# Lines starting with # or ; are comments.


[Theme]
# Colors are defined as R, G, B, A (0-255)
bg = 44, 37, 37, 255        # base
idle = 36, 31, 31, 255      # mantle
hover = 58, 49, 50, 255     # surface0
border = 250, 189, 47, 255  # accent
ripple = 253, 104, 131, 255 # rose
overlay = 44, 37, 37, 200   # base w/ transparency
text = 230, 217, 219, 255   # text

[Settings]
# Width
width = 1100
# Height
height = 560
# The maximum number of wallpapers to load from the directory.
max_wallpapers = 512
# The base size of the square thumbnail images.
base_thumb_size = 240
# The base padding between thumbnails.
base_padding = 28
# The thickness of the glowing border on hover.
border_thickness_bloom = 1.0
# The number of threads to use for loading thumbnail images.
max_threads = 16
# The speed of all layout and hover animations. Higher is faster.
anim_speed = 28.0
# The number of particles to emit on selection.
particle_count = 50
# The duration of the Ken Burns (pan/zoom) effect in preview mode.
ken_burns_duration = 15.0
# The maximum frames per second.
max_fps = 200

[Effects]
# Available effects: none, glitch, blur, pixelate, shake, collapse, reveal
startup_effect = none
keypress_effect = none
exit_effect = none
