general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(268bd2ff) rgba(839496ff) 45deg
    col.inactive_border = rgba(073642ff)
}
