# Hellpaper Configuration File
# Lines starting with # or ; are comments.



[Theme]
# Solarized Dark
bg = 0, 43, 54, 230          # base03
idle = 7, 54, 66, 255        # base02
hover = 88, 110, 117, 255    # base01
border = 38, 139, 210, 255   # blue
ripple = 108, 113, 196, 255  # violet (Solarized purple accent)
overlay = 0, 43, 54, 200     # base03 w/ transparency
text = 131, 148, 150, 255    # base0


[Settings]
# Width
width = 1100
# Height
height = 560
# The maximum number of wallpapers to load from the directory.
max_wallpapers = 512
# The base size of the square thumbnail images.
base_thumb_size = 240
# The base padding between thumbnails.
base_padding = 28
# The thickness of the glowing border on hover.
border_thickness_bloom = 1.0
# The number of threads to use for loading thumbnail images.
max_threads = 16
# The speed of all layout and hover animations. Higher is faster.
anim_speed = 28.0
# The number of particles to emit on selection.
particle_count = 50
# The duration of the Ken Burns (pan/zoom) effect in preview mode.
ken_burns_duration = 15.0
# The maximum frames per second.
max_fps = 200

[Effects]
# Available effects: none, glitch, blur, pixelate, shake, collapse, reveal
startup_effect = none
keypress_effect = none
exit_effect = none
