#include "hellpaper.h"

const char *postProcessingFs =
    "#version 330 core\n"
    "in vec2 fragTexCoord;\n"
    "out vec4 finalColor;\n"
    "uniform sampler2D texture0; uniform sampler2D bloomTexture; uniform sampler2D bloomTextureHiRes;\n"
    "uniform float time; uniform vec2 resolution;\n"
    "uniform float glitchIntensity; uniform float blurIntensity;\n"
    "uniform float pixelSize; uniform int mirrorMode;\n"
    "uniform float shakeIntensity; uniform float collapseIntensity;\n"
    "uniform float scanlineIntensity;\n"
    "const float bloomFactor = 1.0; const float vignetteStrength = 0.3;\n"
    "const float grainStrength = 0.04;\n"
    "float random(vec2 st) { return fract(sin(dot(st.xy, vec2(12.9898,78.233))) * 43758.5453123); }\n"
    "vec2 barrelDistortion(vec2 uv, float strength) { vec2 p=uv*2.0-1.0; float r2=dot(p,p); p*=(1.0+strength*r2); return p*0.5+0.5; }\n"
    "void main() {\n"
    "    vec2 uv = fragTexCoord;\n"
    "    if (shakeIntensity > 0.0) { uv += vec2(random(vec2(time*10.0))-0.5, random(vec2(time*10.0+0.5))-0.5) * shakeIntensity * 0.1; }\n"
    "    if (pixelSize > 1.0) { uv = floor(uv * pixelSize) / pixelSize; }\n"
    "    if (mirrorMode == 1) uv.x = 1.0 - uv.x;\n"
    "    if (collapseIntensity > 0.0) { uv = barrelDistortion(uv, collapseIntensity*2.0); if(length(uv*2.0-1.0) > 1.0-collapseIntensity) {discard;} }\n"
    "    vec3 baseColor = vec3(0.0);\n"
    "    if (blurIntensity > 0.0) { \n"
    "        vec2 center = vec2(0.5); \n"
    "        baseColor += texture(texture0, uv).rgb; \n"
    "        for (int i = 1; i < 10; i++) { \n"
    "           vec2 offset = normalize(uv - center) * blurIntensity * float(i)/100.0; \n"
    "           baseColor += texture(texture0, uv + offset).rgb; \n"
    "           baseColor += texture(texture0, uv - offset).rgb; \n"
    "        } baseColor /= 21.0; \n"
    "    } else { baseColor = texture(texture0, uv).rgb; }\n"
    "    if (glitchIntensity > 0.0) { \n"
    "       float lineJitter = random(vec2(uv.y * 10.0, time)) * 0.03 * glitchIntensity; \n"
    "       float blocky = random(vec2(floor(uv.y*10.0)/10.0, time)) > 0.95 ? 0.1 : 0.0; \n"
    "       baseColor.r = texture(texture0, uv + vec2(lineJitter + blocky, 0.0)).r; \n"
    "       baseColor.g = texture(texture0, uv).g; \n"
    "       baseColor.b = texture(texture0, uv - vec2(lineJitter, 0.0)).b; \n"
    "    }\n"
    "    vec4 bloomColor = texture(bloomTexture, uv);\n"
    "    vec4 bloomColorHiRes = texture(bloomTextureHiRes, uv);\n"
    "    vec3 combinedColor = baseColor + (bloomColor.rgb + bloomColorHiRes.rgb) * bloomFactor;\n"
    "    float vignette = 1.0 - vignetteStrength * pow(length(fragTexCoord * 2.0 - 1.0), 2.0);\n"
    "    combinedColor *= vignette - collapseIntensity;\n"
    "    if (scanlineIntensity > 0.0) { combinedColor *= (1.0 - (sin(fragTexCoord.y * 400.0) * 0.5 + 0.5) * scanlineIntensity * 0.1); }\n"
    "    float grain = (random(fragTexCoord + time) - 0.5) * grainStrength;\n"
    "    combinedColor += grain;\n"
    "    finalColor = vec4(combinedColor, 1.0);\n"
    "}";

const char *blurFs =
    "#version 330 core\n"
    "in vec2 fragTexCoord;\n"
    "out vec4 finalColor;\n"
    "uniform sampler2D texture0;\n"
    "uniform vec2 renderSize;\n"
    "uniform bool horizontal;\n"
    "const float weight[5] = float[](0.227027, 0.1945946, 0.1216216, 0.054054, 0.016216);\n"
    "void main() {\n"
    "    vec2 texel = 1.0/renderSize;\n"
    "    vec3 result = texture(texture0, fragTexCoord).rgb * weight[0];\n"
    "    if(horizontal) {\n"
    "        for(int i=1; i<5; i++) {\n"
    "            result += texture(texture0, fragTexCoord + vec2(texel.x*i, 0.0)).rgb * weight[i];\n"
    "            result += texture(texture0, fragTexCoord - vec2(texel.x*i, 0.0)).rgb * weight[i];\n"
    "        }\n"
    "    } else {\n"
    "        for(int i=1; i<5; i++) {\n"
    "            result += texture(texture0, fragTexCoord + vec2(0.0, texel.y*i)).rgb * weight[i];\n"
    "            result += texture(texture0, fragTexCoord - vec2(0.0, texel.y*i)).rgb * weight[i];\n"
    "        }\n"
    "    }\n"
    "    finalColor = vec4(result, 1.0);\n"
    "}";
