general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(9279aaff) rgba(f4b999ff) 45deg
    col.inactive_border = rgba(4a2036ff)
}

