general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(f2a7c4ff) rgba(f4f6faff) 45deg
    col.inactive_border = rgba(2f3e60ff)
}
