general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(7dcfffff) rgba(a9b1d6ff) 45deg
    col.inactive_border = rgba(32344aff)
}

