# Hellpaper Configuration File
# Lines starting with # or ; are comments.

[Theme]
bg = 17, 28, 24, 255        # #111c18
idle = 35, 55, 43, 255      # #23372B
hover = 80, 148, 117, 255   # #509475
border = 47, 209, 143, 255  # #2fd18f
ripple = 84, 158, 106, 255  # #549e6a
overlay = 17, 28, 24, 200   # base w/ transparency
text = 193, 196, 151, 255   # #C1C497

[Settings]
# Width
width = 1100
# Height
height = 560
# The maximum number of wallpapers to load from the directory.
max_wallpapers = 512
# The base size of the square thumbnail images.
base_thumb_size = 240
# The base padding between thumbnails.
base_padding = 28
# The thickness of the glowing border on hover.
border_thickness_bloom = 1.0
# The number of threads to use for loading thumbnail images.
max_threads = 16
# The speed of all layout and hover animations. Higher is faster.
anim_speed = 28.0
# The number of particles to emit on selection.
particle_count = 50
# The duration of the Ken Burns (pan/zoom) effect in preview mode.
ken_burns_duration = 15.0
# The maximum frames per second.
max_fps = 200

[Effects]
# Available effects: none, glitch, blur, pixelate, shake, collapse, reveal
startup_effect = none
keypress_effect = none
exit_effect = none
