exec-once = ~/bin/launch-lock-screen
exec-once = waybar
exec-once = swayosd-server
exec-once = mako
exec-once = swww-daemon
exec-once = ~/dev/dashboard/build/topdash
exec-once = ~/bin/launch-hypridle
exec-once = ~/bin/launch-hyprsunset
exec-once = ~/bin/launch-cliphist
exec-once = ~/bin/reload-dashboard
exec-once = ~/bin/launch-obs-log-notify
exec-once = ~/bin/watch-discordspace
