exec-once = hyprpm reload -n
exec-once = hyprlock --delay 1
exec-once = waybar
exec-once = swayosd-server
exec-once = ~/bin/launch-ward
exec-once = awww-daemon
exec-once = ~/dev/dashboard/build/topdash
exec-once = ~/bin/launch-hypridle
exec-once = ~/bin/launch-hyprsunset
exec-once = ~/bin/launch-cliphist
exec-once = ~/bin/reload-dashboard
exec-once = ~/bin/launch-obs-log-notify
exec-once = ~/bin/watch-discordspace
exec-once = eval $(gnome-keyring-daemon --start --components=secrets)
exec-once = dbus-update-activation-environment --all
