#############################
### ENVIRONMENT VARIABLES ###
#############################

env = GTK_THEME,Adwaita:dark
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Simp1e-Tokyo-Night
env = GTK_ICON_THEME,Papirus

env = PATH,/home/dxle/bin:/home/dxle/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
env = WLR_DRM_DEVICES,/dev/dri/card2
env = AQ_DRM_DEVICES,/dev/dri/card2:/dev/dri/card1
env = AMD_PERF_LEVEL=high

misc {
    vfr = false
}
