#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Nordzy-cursors

env = WLR_DRM_DEVICES,/dev/dri/card2
env = AQ_DRM_DEVICES,/dev/dri/card2:/dev/dri/card1
env = AMD_PERF_LEVEL=high

misc {
    vfr = false
}
