general {
    lock_cmd = pidof swaylock || /home/dxle/bin/launch-lock-screen
    before_sleep_cmd = pidof swaylock || /home/dxle/bin/launch-lock-screen
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 600                                 # 10min
    on-timeout = hyprctl dispatch exec /home/dxle/bin/launch-lock-screen  # lock screen when timeout has passed
}

listener {
    timeout = 1200                                                    # 20 min
    on-timeout = hyprctl dispatch dpms off && powerprofilesctl set power-saver  # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && powerprofilesctl set performance  # screen on when activity is detected after timeout has fired.
}


