################
### MONITORS ###
################

monitor=DP-1,1920x1080@144,0x0,1
monitor=HDMI-A-1,2560x1440@144.01,1920x0,1.25
monitor=eDP-2,disable
#monitor=eDP-2,2560x1440@165,4480x0,1 # use this to enable laptop monitor

# workspace-monitor bindings
workspace = 1, monitor:HDMI-A-1, persistent:false
workspace = 2, monitor:HDMI-A-1, persistent:false
workspace = 3, monitor:HDMI-A-1, persistent:false
workspace = 4, monitor:HDMI-A-1, persistent:false
workspace = 5, monitor:HDMI-A-1, persistent:false
workspace = 6, monitor:HDMI-A-1, persistent:false
workspace = 7, monitor:HDMI-A-1, persistent:false
workspace = 8, monitor:HDMI-A-1, persistent:false
workspace = 9, monitor:HDMI-A-1, persistent:false
workspace = special:discordspace, monitor:HDMI-A-1, persistent:false
workspace = special:mediaspace, monitor:HDMI-A-1, persistent:false
workspace = special:scratchpad, monitor:HDMI-A-1, persistent:false
workspace = special:socialspace, monitor:HDMI-A-1, persistent:false
workspace = 10, monitor:DP-1, persistent:true
