###############
### WINDOWS ###
###############

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Make kitty & alacritty transparent
windowrule = opacity 0.92 0.92 0.92, match:class kitty
windowrule = opacity 0.92 0.92 0.92, match:class Alacritty

# Give these windows custom opacity
windowrule = opacity 1 1.06 1.06, match:class chrome-chatgpt.com__-Default

# Make these windows opaque no matter what
windowrule = opaque on, match:class chromium
windowrule = opaque on, match:class Brave
# windowrule = opaque on, match:class chrome-chatgpt.com__-Default

# Make terminals with this tag spawn floating and send it
# it to 'term' special workspace
windowrule {
    name = native-floating-terminal
    float = on
    size = 1000 800
    match:tag = scratchterm
    center = on
    pin = on
}

# Make these windows spawn in the special workspace on any spawn
windowrule {
  name = float-localsend
  match:class = ^(localsend)$
  float = on
  center = on
  animation = slide bottom
}
windowrule {
  name = move-discord-to-discordspace
  match:class = ^(vesktop)$
  workspace = special:discordspace
  size = 1200 800
  float = on
  center = on
  animation = slide bottom
}
windowrule {
  name = move-spotify-to-mediaspace
  match:class = ^(spotify)$
  workspace = special:mediaspace
  size = 1200 800
  float = on
  center = on
  animation = slide bottom
}
windowrule {
  name = move-instagram-to-mediaspace
  match:class = ^chrome-instagram\.com__.*$
  workspace = special:socialspace
  size = 1200 800
  float = on
  center = on
  animation = slide bottom
}
windowrule {
  name = move-tiktok-to-mediaspace
  match:class = ^chrome-tiktok\.com__.*$
  workspace = special:socialspace
  size = 1200 800
  float = on
  center = on
  animation = slide bottom
}

# layer rules
layerrule {
  name = mako-slide-right
  match:namespace = notifications
  animation = slide right
}

layerrule {
  name = waybar-slide-top
  match:namespace = waybar
  animation = slide top
}

