###############
### WINDOWS ###
###############

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Make kitty & alacritty transparent
windowrule = opacity 0.92 0.92 0.92, match:class kitty
windowrule = opacity 0.92 0.92 0.92, match:class Alacritty

# Make chromium and brave opaque no matter what
windowrule = opaque on, match:class chromium
windowrule = opaque on, match:class Brave

# Make terminals with this tag spawn floating and send it
# it to 'term' special workspace
windowrule {
    name = native-floating-terminal
    float = on
    size = 1000 800
    match:tag = scratchterm
    center = on
    pin = on
}

