# Workspace-Specific Rules

workspace = 10, layout:dwindle

### Special workspaces
workspace = special:mediaspace, on-created-empty:~/bin/launch-spotify
workspace = special:discordspace, on-created-empty:~/bin/launch-discord
