general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(8be9fdff) rgba(f8f8f2ff) 45deg
    col.inactive_border = rgba(44475aff)
}
