general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(e5e9f0ff) rgba(d8dee9ff) 45deg
    col.inactive_border = rgba(3b4252ff)
}
