general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(dbbc7fff) rgba(d3c6aaff) 45deg
    col.inactive_border = rgba(475258ff)
}
