# Hellpaper Configuration File
# Lines starting with # or ; are comments.


[Theme]
bg = 45, 53, 59, 230 # #2d353b
idle = 52, 63, 68, 255      # #343f44
hover = 61, 72, 77, 255     # #3d484d
border = 219, 188, 127, 255 # #dbbc7f
ripple = 214, 153, 182, 255 # #d699b6
overlay = 45, 53, 59, 200   # base w/ transparency
text = 211, 198, 170, 255   # #d3c6aa


[Settings]
# Width
width = 1100
# Height
height = 560
# The maximum number of wallpapers to load from the directory.
max_wallpapers = 512
# The base size of the square thumbnail images.
base_thumb_size = 240
# The base padding between thumbnails.
base_padding = 28
# The thickness of the glowing border on hover.
border_thickness_bloom = 1.0
# The number of threads to use for loading thumbnail images.
max_threads = 16
# The speed of all layout and hover animations. Higher is faster.
anim_speed = 28.0
# The number of particles to emit on selection.
particle_count = 50
# The duration of the Ken Burns (pan/zoom) effect in preview mode.
ken_burns_duration = 15.0
# The maximum frames per second.
max_fps = 200

[Effects]
# Available effects: none, glitch, blur, pixelate, shake, collapse, reveal
startup_effect = none
keypress_effect = none
exit_effect = none
