reverse=false
duration=5.2
transition=wipe
transition-duration=3.2
transition-angle=0
transition-step=180
transition-fps=120
transition-pos=center
transition-bezier=.54,0,.34,.99
transition-wave=20,20
